// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usyccoijwkthdaesafmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzeWNjb2lqd2t0aGRhZXNhZm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTcyNzYsImV4cCI6MjA3NDE5MzI3Nn0.htJSS_r6VI31IruBEleEr8PWWQnbpqGqA8JVQJ1jB9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});